# Linked-list

all: myllist

OBJFILES=myllist.o 
MYLLIST_OBJFILES=myllist.o myllist-example.o

myllist: $(MYLLIST_OBJFILES)
	$(CC) -o $@ $(MYLLIST_OBJFILES)

clean:
	rm -f $(MYLLIST_OBJFILES) myllist
